### PR TITLE
Delay Protocol Server

### PR DESCRIPTION
**Pull request by linuxlewis**
Here's a first version of an implementation for #115.

Welcome any feedback or suggestions, here's a few questions I am looking for thoughts on:
- How/should delay messages be persisted?
  - I think a django model is an option here. Celery beat uses shelves by default which could also be done.
- Should the delay channel name be configurable?
## Quick start

Here's how you run the server.

``` bash
python manage.py rundelay
```

Then send a message to `channels.delay` that has the keys `content`, `channel`, and `delay` to delay it.

``` python
content = { 'content': {'x': 1}, 'channel': 'test.math', delay: 10 }
Channel('channels.delay').send(content, True)
```

### CODE REVIEW

**Comment by andrewgodwin** [comment]
I think a Django model is probably the best way, given that Channels is a Django app. I'd be tempted to say maybe the delay server should even be its own separate Django app so the models can be limited to install if you add it to INSTALLED_APPS?

I think the channel name should not be configurable - the protocol specs so far all have fixed names (e.g. `http.request`) as that's part of what you code against. I do wonder if we should call it `__channels__.delay` or something more similar though, or if the `channels` namespace could just be kept as a reserve.

**Comment by linuxlewis** [comment]
I think keeping the `channels.*` namespace reserved is reasonable. I might suggest to go as far as to enforce this in the router or `runworker` with an error so it's clear to users.

I actually think a separate django app is a great idea. Especially if this continues to evolve into #74

How do you feel about making the storage configurable? I think a django model is a fine default but maybe it's possible someone would prefer a local memory or redis backend option.

**Comment by andrewgodwin** [comment]
I would say no to configurable storage (my policy is to say no to generic abstractions unless there's a real need) - if someone wants different behaviour, I think they should write their own delay server against the specification we'll come up with, since that's the real abstraction (and they might be able to structure the storage interaction better, e.g. async calls to the datastore if possible)

**Comment by linuxlewis** [comment]
Added some commits here. Created the channels.delay app and moved everything over. Messages are also now stored using a django model.

I added support for an `interval` parameter so messages can be dispatched periodically.

Any feedback is welcomed

**Comment by andrewgodwin** [comment]
I think it looks pretty good - some questions:

* Do you think it's worth refactoring the Worker code to share between this and `runworker`? I've been pondering having a basic worker loop in `asgiref` which might help this too.
* Could you add a spec for how delays work? There's sub-specs for ASGI in the docs already, which also makes me wonder if we should call it `asgi.delay` or something else without `channels` in it.
* Given that it would be nice to also have crontab-like periodic events emitted from the server without having to initiate them first (as per the "delay every X seconds" stuff you have), maybe it would be best to remove the delay-every-X and have a separate python/statically-configurable method for sending periodic events (the implementation doesn't have to make it in, just want to know what you think)

**Comment by linuxlewis** [comment]
- I think this would be nice to have. Since there was a lot of crossover with `runworker`, I considered actually modifying it to handle the delay logic and exposing it as a  `--delay` option. With that said it feels like out of scope of this PR but definitely a quick refactor.
- Yes defintely! When you say sub-specs I'm assuming you mean something like this? (http://channels.readthedocs.io/en/stable/asgi/email.html)
- I like this idea a lot and it's something I thought about but didn't have a clear idea on how It would work. The current interface accepts a delay parameter as the number of seconds to delay. Do you see this as augmenting that interface to pass an importable string? `{'channel': 'test', 'delay': 'module.callable_that_returns_seconds', 'content': {'x': 1}}`. Or do you see this callable being executed on every worker run?

**Comment by andrewgodwin** [comment]
* Let's keep that out of this PR but consider it once it's merged, as I think it would be widely valuable.
* I do mean something exactly like that.
* I mean not having it configured via channels at all (as you can lose messages over channels), but having just a Django setting or similar that configures it. Just a list of channel, payload, and interval would work.

**Comment by linuxlewis** [comment]
Ok put some more commits up.

- There's now an official ASGI spec. I changed the name of the channel from `channels.delay` to `asgi.delay` to make it less of a channels specific thing.
- interval functionality has been removed
- changed default unit from seconds to milliseconds. This is largely from feedback other developers I spoke to about the feature.

Let me know your thoughts.

**Comment by andrewgodwin** [comment]
Yup, this seems lovely now. Sorry about the delay in getting back to you - anything else you want to add or should I merge it?

**Comment by linuxlewis** [comment]
No worries, appreciate your feedback on this. Merge away 👍

**Comment by andrewgodwin** [comment]
Thanks for your work on this!

**Comment by sachinrekhi** [comment]
Great work on this guys! Looking forward to giving it a try.

One question: after looking at the implementation, it seems like if I ever need to reschedule / remove some delayed tasks, I can directly manipulate the Django model to change the due_date or just delete the model object entirely correct? It looks like in the delay server run loop it makes a live db query each time, so looks like I shouldn't run into any caching issues or such, right?

**Comment by andrewgodwin** [comment]
Well, that's not an officially documented way, so I can't say it'll work forever, but yes, that would work for now.

**Pull request merged**
