### PR TITLE
[JS client] fix callback parameter name : action => payload

### PR DESCRIPTION
**Pull request by pchiquet**
this variable is set to "msg.payload" when a message is received

### CODE REVIEW

**Comment by proofit404** [comment]
Hi

I wonder if it is just a variable name change?

**Comment by andrewgodwin** [comment]
This patch doesn't seem to have any actual external effect - did you just want to rename it internally?

Also, if you're submitting a JavaScript PR, please recompile the built versions and include those in the diff as we don't have a build process for JS.

**Comment by pchiquet** [comment]
Hi,
- it is only a variable name change in the callback called when any websocket message is received (this callback passes the full message payload, and not "payload.action")
- I have updated the README to reflect these changes
- I have recompiled with "npm run compile"
- the tests pass (launched with "npm run test")

**Comment by andrewgodwin** [comment]
Thanks!

**Pull request merged**
