### PR TITLE
Skip Daphne installation based on env var

### PR DESCRIPTION
**Pull request by oTree-org**
Fixes issue: https://github.com/django/channels/issues/490

This implementation does not impact the beginner user experience. They will get the same errors as before. I considered the case where for some reason daphne is not present when it should be (e.g. because it got uninstalled). The try/except in apps.py does not silence any actual failures, since as soon as the user tries runserver, they will get a ModuleNotFoundError telling them daphne is missing.

I used a try/except in apps.py instead of checking for the CHANNELS_SLIM_INSTALL env var, because:

(1) the user may have installed daphne separately
(2) maybe the env var was present only during installation. For example, a package author may want to set this env var in their own package's setup.py:

```
os.environ['CHANNELS_SLIM_INSTALL'] = '1'

setup(
    name='my-package',
    install_requires=['channels'],
    # ..
)
```

### CODE REVIEW

**Comment by oTree-org** [comment]
After looking into how pip & wheels work, I need to revise this approach. Closing for now.

**Comment by carltongibson** [comment]
Hey @oTree-org -- OK thanks. 

This looked close. I'm open to something here if we can solve the issues. Will have a think on it... 🧐

**Comment by oTree-org** [comment]
Hi, sorry for my delayed reply. Here is why I think this approach won't work:

- I discovered that pip sometimes installs each package in a separate subprocess. This defeats the "package author" use case of setting the env var dynamically during installation of a package so that it is set by the time channels gets installed.
- More importantly, Channels is distributed as a wheel, so I think setup.py is usually not run during installation.

**Comment by oTree-org** [comment]
(Though the rest of the code in that PR could still be used if someone finds another way to skip daphne installation.)

**Pull request closed without merging**
