### PR TITLE
Added function prototype for BaseChannelLayer

### PR DESCRIPTION
**Pull request by jophy-ye**
Added prototypes like `send()`, `receive()`, etc. to `BaseChannelLayer`, the base class of all channel layers. These are necessary functions for any channel layer, according to the [docs](https://channels.readthedocs.io/en/latest/channel_layer_spec.html).

This helps intellisense when type hints are present, and assists developers writing their own channel.

### CODE REVIEW

**Comment by jophy-ye** [comment]
Refactored code according to linter. Should be ready now! Thanks.

**Comment by jophy-ye** [comment]
Can a maintainer please review my changes? Thank you so much!

**Comment by carltongibson** [comment]
Hi @jophy-ye I've looked at this. I'm not immediately keen, so I'm trying to think over what I actually think here. We don't have typing but I'd lean to a Protocol, rather than null implementations if I really wanted this. (As I say, currently not sure.)

**Comment by jophy-ye** [comment]
@carltongibson Thanks. In my opinion, this is more than a null implementation: it’s extremely common to have a Redis channel layer in production and an in-memory channel for local development. I understand that channels does not accept typing at the moment, but I’d say some developers would like to (in their projects). Having a function prototype in the base class could help with it, but if this doesn’t fit, I’m happy to close this PR.

**Comment by carltongibson** [comment]
@jophy-ye Yes, I'm still pondering it. Please allow me a cycle for that.

**Comment by bigfootjon** [comment]
> We don't have typing but I'd lean to a Protocol

Should we add typing? Separate discussion of course but could solve this class of problems

**Comment by carltongibson** [comment]
@bigfootjon I'm in two minds about that. 😅

Maybe we should, but... 

1. Django doesn't, so... (But perhaps we could show the way)
2. Typing has come on since then — Protocols not least — but last time it was looked at, the annotations weren't pretty (in many places) so I'm reluctant to commit to a "Yes" and then find we're still in that same boat. 

So still pondering that too 😅

**Comment by carltongibson** [comment]
@jophy-ye There is no difference... You define a protocol and then use it in your type annotations, so it's part of the typing effort. 

@bigfootjon Happy to dabble here if you're keen. I'd suggest adding some hints incrementally, starting with obvious and clean ones, and then seeing how that goes.

**Comment by bigfootjon** [comment]
I'm fine with this as-is. @carltongibson since you might have other thoughts here I'll defer to you

**Review by carltongibson — APPROVED** [review]
OK let's have it. Thanks @jophy-ye

**Pull request merged**
