### PR TITLE
Patch rename http client

### PR DESCRIPTION
**Pull request by Krukov**
Ref #601 #586

### CODE REVIEW

**Comment by andrewgodwin** [comment]
I don't think we can just remove it like this entirely - I'd rather make it capable of both (and it seems to be mostly there)?

**Comment by Krukov** [comment]
Yes, maybe removing is wrong way, but I think that separation is necessary. Http client should have more http friendly methods, like get, post ..... I think they do not need to be mixed.

**Comment by andrewgodwin** [comment]
OK, let's do this for now then, I need to sit down and work out the testing stuff properly.

**Comment by ftxrc** [comment]
It would be great if this was in the docs; if I have time I might PR it.

**Comment by andrewgodwin** [comment]
That would be most welcome.

**Pull request merged**
