### PR TITLE
Fix InMemoryChannelLayer growing indefinitely

### LINKED ISSUE #1574: InMemoryChannelLayer grows indefinitely
InMemoryChannelLayer has this in the `_clean_expired` method:

            # Is the channel now empty and needs deleting?
            if not queue:
                del self.channels[channel]

Queues are always truthy even if empty. So that `del` statement will not be reached. I believe the line should be changed to `if queue.empty():`. 

(I saw this while investigating a crash that seems to be due to the channel layer growing indefinitely bigger.)

### PR DESCRIPTION
**Pull request by Kyle-Verhoog**
In `InMemoryChannelLayer` it was possible for channels with expired messages to live indefinitely since the check for deleting them always evaluated to `False`.

Fixes #1574.

### CODE REVIEW

**Review by carltongibson — COMMENTED** [review]
Hi. Thanks for this. All changes need regression tests. Can you add a test case demonstrating the issue?

**Comment by Kyle-Verhoog** [comment]
Sure thing! It seems like the "fix" broke a couple of the tests too so I'll look into that and adding regression tests.

**Comment by Kyle-Verhoog** [comment]
@carltongibson should be good to review now :slightly_smiling_face:

**Review by carltongibson — APPROVED** [review]
Super! Looks good @Kyle-Verhoog — thanks very much. 

Welcome aboard! ⛵️

**Pull request merged**
