### PR TITLE
Updating Channels status regarding inclusion into django core

### PR DESCRIPTION
**Pull request by jibaku**
Updated docs to add information related to Channels being a Django official project.

### CODE REVIEW

**Comment by jibaku** [comment]
And maybe it makes sense to remove the docs/cross-compat.rst file for the moment ?

**Comment by andrewgodwin** [comment]
I agree cross-compat should probably just go. Do you want to include that into this PR?

**Comment by jibaku** [comment]
@andrewgodwin Yes. I've removed the file/reference to it and updated the PR.

**Comment by andrewgodwin** [comment]
Thanks!

**Pull request merged**
