### PR TITLE
Bug fix:  Issue #1588

### PR DESCRIPTION
**Pull request by DanielSwain**
Addresses https://github.com/django/channels/issues/1588

### CODE REVIEW

**Review by carltongibson — COMMENTED** [review]
Hi @DanielSwain, welcome!  

We’re obviously missing some test coverage here. Ideally this would have been picked up by the test suite already. Are you able to add matching regression tests? 

Thanks!

**Comment by DanielSwain** [comment]
@carltongibson Please see [my comment](https://github.com/django/channels/issues/1588#issuecomment-771027880) in the issue message thread that this PR fixes.

**Comment by carltongibson** [comment]
Hey @DanielSwain — OK, thanks for the detail there. 

We need to think about a unit test here though. It should be enough to pass the init args see the error raised no?

**Comment by DanielSwain** [comment]
@carltongibson I hate to admit it, but unfortunately I'm at the edge of my knowledge and am not able to add a unit test.

**Comment by carltongibson** [comment]
Ok, no problem. I shall have a look at it, review what's going on and add the tests. 

Thanks again for the input, and all the extra details! 👍

**Comment by jonaswinkler** [comment]
Hello!

Came over here from #1588, see my latest comment https://github.com/django/channels/issues/1588#issuecomment-772678507 there.

I've tried applying the proposed fix locally, and with the recommended minimal test case according to the documentation (https://channels.readthedocs.io/en/latest/topics/testing.html#setting-up-async-tests), and an empty (just `pass`, see comment) `WebsocketConsumer` implementation, the error goes away, and another error appears.

```
Traceback (most recent call last):
  File "/home/jonas/.local/share/virtualenvs/paperless-RxYopU_u/lib/python3.6/site-packages/asgiref/sync.py", line 147, in __call__
    return call_result.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/jonas/.local/share/virtualenvs/paperless-RxYopU_u/lib/python3.6/site-packages/asgiref/sync.py", line 212, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "/home/jonas/git/paperless/src/paperless/tests/test_websockets.py", line 11, in test_auth
    response = await communicator.get_response()
  File "/home/jonas/.local/share/virtualenvs/paperless-RxYopU_u/lib/python3.6/site-packages/channels/testing/http.py", line 42, in get_response
    response_start = await self.receive_output(timeout)
  File "/home/jonas/.local/share/virtualenvs/paperless-RxYopU_u/lib/python3.6/site-packages/asgiref/testing.py", line 78, in receive_output
    self.future.result()
  File "/home/jonas/.local/share/virtualenvs/paperless-RxYopU_u/lib/python3.6/site-packages/asgiref/compatibility.py", line 34, in new_application
    return await instance(receive, send)
TypeError: __call__() missing 1 required positional argument: 'send'

```

`asgiref` is at version 3.3.1. `channels` at 3.0.3. Let me know if you need anything else.

**Comment by carltongibson** [comment]
Hi @jonaswinkler thanks for the confirmation. 

I just need some bandwidth to sit down with this myself, but I'm a little constrained at the moment (with everything) 

If you were able to contribute a test case that would speed things up, as it would make it much easier to review when I do get a moment. (It makes the needed moment smaller.)

Thanks both!

**Comment by jonaswinkler** [comment]
I did some more digging and came to the following conclusions (all barring the fact that I'm just a user of your libraries and don't know any of the details)

* Sometimes (the exact 'when' still left to figure out), `asgiref` detects WebsocketConsumer subclasses (or other consumers from channels as well) as legacy "double-callables". The visible issue is caused by trying to convert that double callable to a single-callable by invoking the constructor with the scope as an argument (this fails).
* See their `compatibility.py` for details.
* This happens when trying to run test cases with the `HttpCommunicator`.
* Further issues about the missing `send` argument are caused since `asgiref` now expects that consumer to be a "single-callable" and just passes "send" and "receive", but `__call__` of `AsyncConsumer` expects the scope as well, as first argument.

Two possible scenarios:
* `asgiref` incorrectly detects channel consumers as "double-callables".
* `AsyncConsumer` is actually a legacy "double-callable" from pre ASGI v3, and needs updating.

See also https://asgi.readthedocs.io/en/latest/specs/main.html#applications

In any case, *IMHO* the proposed fix does not address the underlying issue.

**Comment by yedpodtrzitko** [comment]
Hi,
I looked into this a bit, and I think found the underlying issue.

here's a test I'm using:
```
@pytest.mark.asyncio
async def test_websocket_consumer_init():
    results = {}

    class TestConsumer(WebsocketConsumer):
        def connect(self):
            results["connected"] = True
            self.accept()

        def receive(self, text_data=None, bytes_data=None):
            results["received"] = (text_data, bytes_data)
            self.send(text_data=text_data, bytes_data=bytes_data)

        def disconnect(self, code):
            results["disconnected"] = code

    communicator = WebsocketCommunicator(TestConsumer, "GET", '/test/')
    connected, _ = await communicator.connect()
```

in this case I'll end up with the error:

```
class WebsocketConsumer(SyncConsumer):
    def __init__(self, *args, **kwargs):
>       super().__init__(*args, **kwargs)
E       TypeError: object.__init__() takes exactly one argument (the instance to initialize)

channels/generic/websocket.py:25: TypeError
```

Changing the test this way fixes the issue:

```diff
-communicator = WebsocketCommunicator(TestConsumer, "GET", '/test/')
+communicator = WebsocketCommunicator(TestConsumer.as_asgi(), "GET", '/test/')
```

So the problem happens when `TestConsumer` is converted to asgi callable elsewhere than in explicit call of `as_asgi()`. That's here in asgiref: 

https://github.com/django/asgiref/blob/master/asgiref/compatibility.py#L33


if I'm not missing anything, then this should be fixed inside asgiref

**Comment by yedpodtrzitko** [comment]
Apparently my assumption about a fix in asgiref was incorrect (see my closed PR above). Using the test from my previous comment with the change proposed in this PR shows that it fixes the consequences of missing `.as_asgi()` in one place, but then another problem will pop up further down the line because the application will be improperly converted to legacy ASGI v2 application, which has a different signature and it ends up with this error instead:

```
    # asgiref/compatibility.py:34: TypeError
    async def new_application(scope, receive, send):
        instance = application(scope)
>       return await instance(receive, send)
E       TypeError: __call__() missing 1 required positional argument: 'send'
```

One option could be `ApplicationCommunicator` would detect `.as_asgi()` wasn't called and do it automatically. But that won't stop people writing wrong code and it will add more compatibility clutter. 

It could throw an error when it receives such application? The tricky part could be detecting that it's ASGI v3 application instead of legacy v2 or v4 in future. So maybe `AsyncConsumer` could have a parameter like `asgi_version = 3` or similar, which could help detect what version of ASGI application are we dealing with, and do the right thing (whatever option will be).

**Comment by carltongibson** [comment]
Closing in favour of #1724. Thanks @DanielSwain!

**Pull request closed without merging**
