### PR TITLE
Improve docs consistency on query strings

### PR DESCRIPTION
**Pull request by ftxrc**
Change to room_name parameter and erase references to query strings throughout the documentation tutorial.

### CODE REVIEW

**Comment by andrewgodwin** [comment]
Yup, that's better, thanks!

**Comment by dsanders11** [comment]
This has already been merged, but @ftxrc did ask for a thorough review.

While it removed the query string inconsistency, now the documentation doesn't explain where `room_name` is coming from, and the example code is wrong.

The `routing.py` example for the `Persisting Data` section does not extract the room name from the URL path, so the example code under `Persisting Data` is incomplete. This could be fixed by updating the `routing.py` example, but then it would be using a feature that isn't explained until later in the `Routing` section (not the end of the world). In order to match with the code it would also need to have the URL path in all three WS message types, unlike the later `Routing` section which only pulls `room_name` for `ws_add`.

My 2 cents.

**Comment by ftxrc** [comment]
@dsanders11 I'll definitely explain it a bit more in a bit. I did add it to the routing.py, just the main one however; that one seems to be called in the main rooms.py where the websocket calls are routed.

```
chat_routing = [
    route("websocket.connect", chat_connect, path=r"^/(?P<room_name>[a-zA-Z0-9_]+)/$"),
    route("websocket.disconnect", chat_disconnect),
]
```
However, reading it again, some things in it are slightly wrong; I'll fix them in about 30 mins.

**Comment by dsanders11** [comment]
> I did add it to the routing.py, just the main one however; that one seems to be called in the main rooms.py where the websocket calls are routed.

But you missed the one [in `Persisting Data`](http://channels.readthedocs.io/en/stable/getting-started.html#persisting-data) right after the example code. Right after the code you updated to add the `room_name` argument, it says "Update routing.py as well:" and that code does not include the URL path for `room_name`. Lines ~410-430.

**Comment by ftxrc** [comment]
@dsanders11 I'll see; I'll do this once I have lunch. Forgot about yesterday haha, will take a look and fix.

**Pull request merged**
