### PR TITLE
Lint with flake8 on CI

### PR DESCRIPTION
**Pull request by adamchainz**
For some reason there's flake8 configuration in setup.cfg, whilst only sub-tool pyflakes was running on CI.

### CODE REVIEW

**Review by carltongibson — COMMENTED** [review]
Yep, super. 👍

**Review by carltongibson — APPROVED** [review]

**Comment by adamchainz** [comment]
Modified to:

* Use [black compatible config](https://black.readthedocs.io/en/stable/compatible_configs.html#flake8)
* Fix all violations
* Run tools on CI via `tox` so less copy-paste.

**Comment by adamchainz** [comment]
Hey, I'm working on this! 👀

**Comment by carltongibson** [comment]
We have a black/flake8 fight. It's my bedtime so I'll leave it to you! 🙂

**Comment by adamchainz** [comment]
Okay I force pushed over your force push, I think we were doing basically the same things...

**Comment by carltongibson** [comment]
You can merge when you're happy! Thanks @adamchainz!

**Comment by adamchainz** [comment]
> You’re not authorized to merge this pull request.
😅

**Comment by carltongibson** [comment]
Hmmm no idea why that it. (Will look tomorrow...)

In the meantime...

**Review by carltongibson — APPROVED** [review]

**Pull request merged**
