### PR TITLE
Documentation: running workers with uWSGI

### PR DESCRIPTION
**Pull request by bastianh**
Since there are sections about hosting Django with gunicorn and uWSGI in the main Django documentation I thought it might also be a good idea to show examples how to run channel worker / interfaces when using those.

Maybe there should be a seperate page for examples ?

### CODE REVIEW

**Comment by andrewgodwin** [comment]
Yes, there should probably be a separate section for different deployment methods - a uWSGI one would need to cover deploying a WebSocket server too, though, since while mules can run the workers, they can't run arbitary socket listeners.

Do you know of a way to get uWSGI to hand over raw incoming socket connections to something that can handle them? It's possible that would be enough to pass off the rest of the work to a WebSocket implementation we already have, though at that point you're using uWSGI as little more than a process manager.

**Comment by bastianh** [comment]
I have never done this, but uwsgi can do websockets and it has a routing system to route a path to a different server.

http://uwsgi-docs.readthedocs.org/en/latest/WebSockets.html

Until now I've always redirected websockets directly in nginx

**Comment by bastianh** [comment]
Here is described how you can route requests to an other uwsgi or webserver. (http://uwsgi-docs.readthedocs.org/en/latest/InternalRouting.html)

But I guess most uwsgi users use nginx so an example conf with redirecting in nginx would also be nice.

**Comment by andrewgodwin** [comment]
The uwsgi websockets module is unfortunately too high-level to easily plug into the existing code; someone would have to write code specifically from scratch to run on uwsgi's implementation. I'm sure someone will.

**Comment by auvipy** [comment]
there is django-websocket-redis which use uWSGI webSocket in django project

**Comment by nemesisdesign** [comment]
exactly, maybe here there's something interesting:
https://github.com/jrief/django-websocket-redis/blob/master/ws4redis/uwsgi_runserver.py

**Comment by ZuSe** [comment]
+1

**Comment by ssteinerx** [comment]
I'm building out a setup like this with Docker, but the configuration should be pretty similar.  I'm planning on asking for the whole thing to be added to the [channels-examples](https://github.com/andrewgodwin/channels-examples) repo when I'm done with it this week.  It goes from naked Django through a Dockerized deployment, step by step.

**Comment by andrewgodwin** [comment]
Closing for now till we can get a full separate example with daphne running too.

**Comment by eukreign** [comment]
@ssteinerx Any luck with your example? Would be useful to have.

**Comment by ssteinerx** [comment]
@eukreign I had to go with a more traditional setup and, unfortunately, the Docker project had to be put aside for the moment.

**Comment by ZuSe** [comment]
@andrewgodwin  Why would you close it? I really like the idea. It would avoid deploying one more component, especially for websites that are already running Django with uwsgi. Just leave it open until we find a way how to do it, it's kinda independent from daphne, isn't it?

**Comment by andrewgodwin** [comment]
@ZuSe: It's closed because as far as I could tell it couldn't be done, as uWSGI does not expose a low-level enough API to integrate with Daphne (it would instead need native ASGI support, and that is something for the uwsgi project to tackle if they wish)

**Comment by mostaszewski** [comment]
Has anyone managed to run Django Channels' websockets on uWSGI? I would like to avoid using Daphne and stay with the uWSGI.

**Pull request closed without merging**
