### PR TITLE
Make the channel_session decorator work on methods as well

### PR DESCRIPTION
**Pull request by ErwinJunge**
I've modified the `channel_session` decorator so that it can be used on methods of class-based consumers as well.

### CODE REVIEW

**Comment by proofit404** [comment]
Any tests for this improvement?

**Comment by ErwinJunge** [comment]
@proofit404 Added tests

**Comment by andrewgodwin** [comment]
The one change I would probably make to this is only checking the first two arguments; I'm worried that this is a little bit too permissive about where the message is allowed to be in the argument list. Otherwise, I like it.

**Comment by ErwinJunge** [comment]
@andrewgodwin Done :)

**Comment by andrewgodwin** [comment]
Great, thanks!

**Pull request merged**
