### PR TITLE
added http_timeout as a command line option for runserver

### PR DESCRIPTION
**Pull request by RockHoward**
Only added http_timeout. I am prepared to add other command line options upon request.

### CODE REVIEW

**Comment by RockHoward** [comment]
Those tests failed because the test expected http_timeout to be passed in to the server as None instead of 60.

This seems bogus since the value was hard-coded to 60 before I made my change.

**Comment by andrewgodwin** [comment]
It's just mocking so it's very fragile - just fix the assertion in the pull request too so it passes.

**Comment by RockHoward** [comment]
Gotcha. Hopefully I will have a few minutes to get this done this evening.

**Comment by andrewgodwin** [comment]
Lovely, thanks!

**Pull request merged**
