### PR TITLE
User friendly way to close websocket with code (via CloseException)

### PR DESCRIPTION
**Pull request by Krukov**
@andrewgodwin what do you think about it?

### CODE REVIEW

**Comment by andrewgodwin** [comment]
Hmm, I avoided doing this so far as I didn't want another way to do it, but there are definitely advantages, not least allowing some of the decorators to close stuff properly.

My main concern is how it's websocket specific, but has to be written directly into the worker; it would be nice if we could have a slightly more generic way that allowed closing of other protocols like this without people having to have their own Worker class. I'm thinking something like a base ChannelSocketException where subclasses get `.run()` or something when they're caught by the worker, and so the WebsocketCloseException can have a `run()` that sends `close=code`

**Comment by Krukov** [comment]
:+1:  I will correct it soon.

**Comment by Krukov** [comment]
@andrewgodwin It is more suitable solution?

**Comment by andrewgodwin** [comment]
Yes! If you could fix the import sorting error I'll merge this.

**Comment by Krukov** [comment]
Done!

**Comment by andrewgodwin** [comment]
Thanks!

**Pull request merged**
