### PR TITLE
Add Django3 compat code in doc example code

### PR DESCRIPTION
**Pull request by AmirMahmood**
Example code In custom authentication doc doesn't work with Django3 and raises `django.core.exceptions.SynchronousOnlyOperation`.
This is a fix as a follow up to this issue: #1399.

### CODE REVIEW

**Comment by carltongibson** [comment]
Looks like we need to update the Twisted dependencies (or pin attrs...) Will look at this in the week.

**Comment by jheld** [comment]
Any concerns that this is higher priority re:django 3.1? The triage/resolution, in particular.

**Comment by Ian-Foote** [comment]
@carltongibson Since this is a docs-only change, can it be merged despite the CI failure? (Is that fixed in master anyway?)

**Comment by carltongibson** [comment]
Yep good. Thanks for the hustle.

**Pull request merged**
