### PR TITLE
Add GitHub issue template

### PR DESCRIPTION
**Pull request by ssteinerx**
Add an issue template to ask the questions that have to be asked on every bug report etc.

Basic version information, behaviour, expected behaviour, how are you connected etc. that seems to have to be established for every issue.

Should save some time...

### CODE REVIEW

**Comment by andrewgodwin** [comment]
Thanks - I had forgot you could do this.

**Comment by shaib** [comment]
We're now seeing a limitation of github issues: The issue describing this very change would not fit the template very well.

**Comment by ssteinerx** [comment]
The template is just a suggestion and asks for the information common to issues related to the project.  It's not perfect, but should reduce the repeated "What version of channels..." that seem to have to be asked on almost every issue related to channels itself.

**Comment by shaib** [comment]
Don't get me wrong: I'm sure this template is an improvement to the project, and it's a Good Thing(TM) that you added it. The criticism wasn't against this patch, but against GitHub Issues.

**Comment by senden9** [comment]
Comments are also possible in templates. Syntax:
`<!--- This comment is only visible in the write mode. Not in the final issue. -->`
We could add a comment that says that this is just a suggestion if this makes the things more clearly.

**Comment by andrewgodwin** [comment]
I will modify the template to be a bit more generic regardless.

**Comment by ssteinerx** [comment]
Wasn't meant to be final, more of a reminder...

**Comment by andrewgodwin** [comment]
I appreciate the reminder! Thanks for bringing this up.

**Pull request merged**
