### PR TITLE
Update supported versions

### PR DESCRIPTION
**Pull request by carltongibson**

### CODE REVIEW

**Comment by carltongibson** [comment]
Hey @andrewgodwin interesting one in https://github.com/django/channels/pull/1513/commits/1e8dad6173d848d1307bad64e72995139f5dbb9c — Adds `django_db` marks for all tests to Sync consumers, since `asgiref` 3.3. (All good, but thought you'd be interested to note. Ta.)

**Comment by smithdc1** [comment]
Hi Carlton, just to check...

So this keeps support for Django 2.2 (which continues to support Python 3.5?) but drops support for Python 3.5 from this package?

**Comment by carltongibson** [comment]
Yes, that’s right. We’ll keep support for 2.2 until 3.2 is out. (But 3.5 is EOL now, and...)

Seem reasonable?

**Comment by smithdc1** [comment]
Yes, given 3.5 is eol my natural preference is to drop support (may be a bit aggressive for some). 

Question came from being a bit unsure as  previously (on crispy-forms, I think) we'd discussed keeping 3.5 support until 2.2 is eol which is some time away.

I think what your saying something different here in that channels will drop 2.2 support circa.1 year before it becomes eol?

**Comment by carltongibson** [comment]
Yes. Happy to keep going until 3.2 is out but if you're doing this stuff you really need to be updated. 

Perhaps I should add a note to that effect to the docs. 🤔

**Comment by carltongibson** [comment]
TBH it depends on the cost. If it's **just** as case of keeping `AsgiHandler` then no harm leaving that there — but what I DO want to communicate is that there's no further working going to go into that (and folks should update to 3.x). 

I plan to add deprecation warnings to that effect. 

1. On `ProtocolTypeRouter` without an `"http"` key. 
2. On instantiating (Channels') `AsgiHandler`.

**Pull request merged**
