### PR TITLE
 Use save's update_fields in serialize_data

### PR DESCRIPTION
**Pull request by AlexejStukov**
pass save's kwargs to serializes so it can access `update_fields` and other.

### CODE REVIEW

**Comment by AlexejStukov** [comment]
With this serialize and serialize_data can react on `update_fields`.

**Comment by andrewgodwin** [comment]
I'm not sure I like the way this passes implementation details of Django signals all the way through to the databinding serializer, or how it only returns the updated fields rather than the whole object every time (I like consistency, and consistency is returning the whole object IMO).

What's the drive to add this? Is there an alternate way that doesn't pass down all the signal arguments and require changing the signature of `serialize`, maybe by special-casing updated fields and using `self` so people could opt into this if they wanted it?

**Comment by AlexejStukov** [comment]
You are probably right about passing the kwargs. My drive for that was, that I periodically updated only one field of a model and did not want to publish the outdated other fields. To ensure that they are always up to date I would have to fetch the instance every time. Are there even other use cases for `update_fields`?

**Comment by andrewgodwin** [comment]
I think that would be the only case; I would prefer to just populate `self.signal_kwargs` in the main repo, not change serialize at all, and let people do update logic like yours in their own subclass.

**Comment by AlexejStukov** [comment]
OK, I changed it accordingly.

**Comment by AlexejStukov** [comment]
Thanks!

**Pull request merged**
