### PR TITLE
Http body handling

### PR DESCRIPTION
**Pull request by hozblok**
Continuation of #1251

### CODE REVIEW

**Comment by carltongibson** [comment]
Super. I was just swinging back round to this myself, so very timely! 🙂

I’m strictly on holiday but I shall have a look this week. 

Thanks!

**Comment by hozblok** [comment]
Hi @carltongibson 

Thanks, as the first exercise I decided to fix the tests a bit. :)
There are no other differences so far (compared to the previous state of 1251 PR).
I plan to implement a scheme with a temporary file in the near future.

**Comment by hozblok** [comment]
Hi @carltongibson ,

It is still useful for #1001 
I think I need to rebase and I’ll think about how this code can be improved. Perhaps the tests for the new handler (StreamedAsgiHandler) should be separate from the main ones (which for AsgiHandler). What do you think?

**Review by carltongibson — COMMENTED** [review]
Hey @hozblok — thanks for the effort here: it's super interesting, and possibly something that could be suggested for Django's `ASGIHandler`, but we'll be dropping the Channel's version ≈soonish and it's not something I ~~want to~~ have the bandwidth to investigate here further. I hope that makes sense. Thanks again.

**Pull request closed without merging**
