### PR TITLE
Require `asgiref` version equal or higher than `3.5.0`

### PR DESCRIPTION
**Pull request by pdonorio**
Given the issue found in #1713, 
updating related requirements, 
to help users who already have the library installed to not face the same problems.

### CODE REVIEW

**Review by carltongibson — APPROVED** [review]
Yes, OK, come on then. Let's have this. Thanks.

**Comment by carltongibson** [comment]
Ah, yes, time to drop `PY36`.

**Comment by pdonorio** [comment]
> Ah, yes, time to drop `PY36`.

Most likely to be a separated PR?

Do you need me to do it, or are you able to? 
Thanks for any support.

**Comment by carltongibson** [comment]
Yes, separate PR — I'm very happy if you'd like to help with that!

**Comment by smithdc1** [comment]
See #1787 for dropping Python 3.6 (and unsupported Django versions).

**Comment by pdonorio** [comment]
Thanks @smithdc1 !

I've just rebased on the updated `main`.

**Comment by smithdc1** [comment]
Thanks for rebasing this. I don't have write access to this repo so we will need @carltongibson to merge.

**Review by carltongibson — APPROVED** [review]

**Pull request merged**
