### PR TITLE
Split path string to path and query strings in WebsocketCommunicator

### PR DESCRIPTION
**Pull request by hoefling**
Fix proposal for #918. Thanks in advance for the review!

### CODE REVIEW

**Comment by andrewgodwin** [comment]
One small niggle - the `query_string` has to be a non-url-decoded bytestring while the `path` has to be a url-decoded unicode string (see the spec here: https://github.com/django/asgiref/blob/master/specs/www.rst), so you need to get those aligned here.

I'd also love to see a test that verifies that!

**Comment by hoefling** [comment]
Sorry for the long delay! Please review the changes, especially if you like the added test. I tried to create a suggestion for testing against the ASGI spec - the `test_connection_scope` is rather primitive, but could be extended to cover the whole spec for the websocket connection scope by adding more validators for each scope field. On the other hand, should you encounter some exotic paths you'd like to check the scope for, just add them to the `paths` list and they will be included in the spec tests.

**Comment by hoefling** [comment]
Or maybe this is an overkill for the simple task of testing the `WebsocketCommunicator`?

**Comment by andrewgodwin** [comment]
Two things:

- I'd prefer to not auto-encode/decode things to `utf8`, but instead to straight up raise errors if the input does not match the required type.
- Just combine the three test communicators into one, IMO. No need to parameterise them like that.

**Comment by hoefling** [comment]
Yeah, I don't like that idea either now. Please review the latest changes!

**Comment by andrewgodwin** [comment]
Looks great, thanks!

**Pull request merged**
