### PR TITLE
Asgi 3 -- BaseMiddleware

### PR DESCRIPTION
**Pull request by jheld**
I also wrote up a draft release notes -- hopefully it's somewhat close to what would be in it normally.

### CODE REVIEW

**Comment by carltongibson** [comment]
Hi @jheld. It's my plan to get to this this week. Thanks.

**Review by carltongibson — COMMENTED** [review]
Hey @jheld — can I ask you to rebase the last two commits here on `master` after I merge #1480. Thanks!

**Comment by jheld** [comment]
@carltongibson I may be a bit late here, my apologies! Just making sure you don't need me to do this (the branch is closed)?

**Comment by carltongibson** [comment]
Hey @jheld. The docs changes are a bit late now yes. (Thanks for those now though) 

The BaseMiddleware simplification could go into master still though, if you have capacity. Thanks!

**Pull request closed without merging**
