### PR TITLE
test: Add python 3.12 and django 5.0

### PR DESCRIPTION
**Pull request by marksweb**
This adds python 3.12 and django 5.0 while dropping python 3.7.

### CODE REVIEW

**Review by carltongibson — APPROVED** [review]
Looks great. Thanks.

**Comment by palfrey** [comment]
Any thoughts about a release with this in?

**Comment by marksweb** [comment]
@palfrey There's no actual code changes to the app here, just testing against django 5 and python 3.12. So you should be able to use these versions with the current releaase.

**Comment by palfrey** [comment]
Huh, you're right! I'd had to upgrade various things when I did a Django 3.2 -> 5.0 upgrade and I must have thought this was one of the ones with problems, but nope. All good, thanks.

**Comment by carltongibson** [comment]
Thanks @marksweb, exactly. 

But for information, I'm pottering towards an update for Daphne at the moment, and then will swing round to Channels again. (Channels-Redis had one just recently.)

**Pull request merged**
