### PR TITLE
Issue#1554: Add support for samesite flag to sessions cookies.

### PR DESCRIPTION
**Pull request by gghildyal**
Address [Issue#1554](https://github.com/django/channels/issues/1554)

### CODE REVIEW

**Review by carltongibson — COMMENTED** [review]
Hi @gghildyal — thanks you rebased. Can you add a small regression test for this? (Just checking set_cookie() or such)

I'm preparing 3.0.1 now. I'd be happy to sneak this in if we can.

Thanks!

**Comment by gghildyal** [comment]
> Hi @gghildyal — thanks you rebased. Can you add a small regression test for this? (Just checking set_cookie() or such)
> 
> Thanks!

No I haven't, just improved the previous fix. Will rebase now and add a test!

**Comment by gghildyal** [comment]
Hi @carltongibson - Added tests now, please review and recommend.

**Comment by gghildyal** [comment]
Hi @carltongibson, I have rebased again so these changes are ready to be merged.

**Comment by gghildyal** [comment]
Hi @carltongibson, Would be good to get this in before the code diverges too much.

**Review by carltongibson — APPROVED** [review]
Thanks for this @gghildyal 👍

**Pull request merged**
