### PR TITLE
Fixed import to resolve RemovedInDjango20Warning

### PR DESCRIPTION
**Pull request by askoretskiy**
That resolves: "RemovedInDjango20Warning: Importing from django.core.urlresolvers is deprecated in favor of django.urls."

### CODE REVIEW

**Comment by andrewgodwin** [comment]
Looks like you need to unindent the last line in your diff to get it to pass.

**Comment by askoretskiy** [comment]
@andrewgodwin Thank you for the hint, have just fixed.

**Comment by andrewgodwin** [comment]
Looks like the import sorter is complaining now! It'll probably want you to move the try/except block below all other imports.

**Comment by askoretskiy** [comment]
Finally no complains ) @andrewgodwin

**Comment by andrewgodwin** [comment]
Hooray! Thanks.

**Comment by askoretskiy** [comment]
@andrewgodwin Are there any plans for 0.17.4 release? I could make respectively PR

**Comment by andrewgodwin** [comment]
No, I plan to do a 1.0 release as the next one, it's just been a very busy time.

**Pull request merged**
