### PR TITLE
Fix an error when using  OriginValidator with python 3.8.11

### PR DESCRIPTION
**Pull request by jtremesay-sereema**
Per documentation, scheme should have a str or bytes type
https://docs.python.org/3/library/urllib.parse.html?highlight=urlparse#urllib.parse.urlparse

I have just checked my fix with the provided testcase in the issue #1716.

### CODE REVIEW

**Review by carltongibson — COMMENTED** [review]
That was quick. 

Can we add a specific test case to channels/tests/security/test_websocket.py?

**Comment by jtremesay-sereema** [comment]
From what I see, this should be tested by the ["normal test"](https://github.com/django/channels/blob/main/tests/security/test_websocket.py#L16).

You didn’t triggered it because your last build (18d in Github Action) is older than the python release (3 days ago).

**Comment by carltongibson** [comment]
Ok, thanks. Let me have a look and check.

**Review by carltongibson — APPROVED** [review]
Yes, super. Thanks. 

It certainly helps if we call the function with the expected types. 

I'll look to roll a release including this fix this week. 

Welcome aboard! ⛵

**Pull request merged**
