### PR TITLE
Don't mutate AsgiHandler state in __call__().

### LINKED ISSUE #1578: Channels 3+ with Django 2.2 under gunicorn/uvicorn fails when hit with concurrent requests
The issue I'm seeing is that with a very barebones Django/Channels/Uvicorn/Gunicorn setup I'm seeing consistent failures when more than one request is made concurrently. Errors included at the bottom.

**Reproduction instructions**

I've made the simplest Django 2.2 LTS project I can at https://github.com/AlexHill/django_channels_test.

Just clone that, then `make env` to create the venv and `make asgi` to start the application server. Then run

```env/bin/python load_test.py 1 10```

to hit it with ten requests serially, which should work fine, and then

```env/bin/python load_test.py 10 10```

to hit it with ten requests in parallel, which should fail.

Downgrading to Channels 2.x makes the problem go away.

**Errors**

```[2020-11-19 06:05:19 +0000] [22144] [ERROR] ASGI callable returned without starting response.```

And sometimes:

```
[2020-11-19 06:05:19 +0000] [22144] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/home/alexh/signiq/uvicorn_test/env/lib/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py", line 391, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/alexh/signiq/uvicorn_test/env/lib/python3.6/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/alexh/signiq/uvicorn_test/env/lib/python3.6/site-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "/home/alexh/signiq/uvicorn_test/env/lib/python3.6/site-packages/channels/http.py", line 200, in __call__
    await self.handle(body_stream)
  File "/home/alexh/signiq/uvicorn_test/env/lib/python3.6/site-packages/asgiref/sync.py", line 304, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 339, in wait_for
    return (yield from fut)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/alexh/signiq/uvicorn_test/env/lib/python3.6/site-packages/asgiref/sync.py", line 343, in thread_handler
    return func(*args, **kwargs)
  File "/home/alexh/signiq/uvicorn_test/env/lib/python3.6/site-packages/channels/http.py", line 258, in handle
    self.send(response_message)
  File "/home/alexh/signiq/uvicorn_test/env/lib/python3.6/site-packages/asgiref/sync.py", line 147, in __call__
    return call_result.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/alexh/signiq/uvicorn_test/env/lib/python3.6/site-packages/asgiref/sync.py", line 212, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "/home/alexh/signiq/uvicorn_test/env/lib/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py", line 535, in send
    raise RuntimeError(msg % message_type)
RuntimeError: Unexpected ASGI message 'http.response.start' sent, after response already completed.
```

### PR DESCRIPTION
**Pull request by AlexHill**
Fixes #1578

### CODE REVIEW

**Review by carltongibson — COMMENTED** [review]
Hi @AlexHill. Thanks for this. 

Can we add _some_ kind of test? (It doesn't need to be perfect, e.g. 0b1bc054ed76b3274b4fbe1db48876e7829386d1)

**Comment by AlexHill** [comment]
Ok, I've added a test that was mostly guessing but does fail without the previous commit. If you are able to run with it at all or make sure it's sensible that would be great. It would be nice to assert something in the test but at the moment, the test will throw a `CancelledError` without the fix. Stack trace below.

```================================================================== FAILURES ==================================================================
______________________________________________________ test_handler_concurrent_requests ______________________________________________________

self = <asgiref.testing.ApplicationCommunicator object at 0x7f7bc882acf8>, timeout = 1

    async def receive_output(self, timeout=1):
        """
        Receives a single message from the application, with optional timeout.
        """
        # Make sure there's not an exception to raise from the task
        if self.future.done():
            self.future.result()
        # Wait and receive the message
        try:
            async with async_timeout(timeout):
>               return await self.output_queue.get()

../../lib/python3.6/site-packages/asgiref/testing.py:74: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <Queue at 0x7f7bc882ae48 maxsize=0>

    @coroutine
    def get(self):
        """Remove and return an item from the queue.
    
        If queue is empty, wait until an item is available.
    
        This method is a coroutine.
        """
        while self.empty():
            getter = self._loop.create_future()
            self._getters.append(getter)
            try:
>               yield from getter
E               concurrent.futures._base.CancelledError

/usr/lib/python3.6/asyncio/queues.py:167: CancelledError

During handling of the above exception, another exception occurred:

    @pytest.mark.django_db
    @pytest.mark.asyncio
    @pytest.mark.filterwarnings("ignore::DeprecationWarning")
    async def test_handler_concurrent_requests():
        """
        Tests request handling ignores anything after more_body: False
        """
        scope = {"type": "http", "http_version": "1.1", "method": "GET", "path": "/test/"}
        handler = MockHandler()
        comm_1 = ApplicationCommunicator(handler, {**scope})
        comm_2 = ApplicationCommunicator(handler, {**scope})
    
        request_1 = comm_1.send_input(
            {"type": "http.request", "body": b"request 1", "more_body": False}
        )
        request_2 = comm_2.send_input(
            {"type": "http.request", "body": b"request 2", "more_body": False}
        )
    
        await request_1
        await request_2
    
>       await comm_1.receive_output(1)  # response start

tests/test_http.py:376: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../lib/python3.6/site-packages/asgiref/testing.py:85: in receive_output
    raise e
../../lib/python3.6/site-packages/asgiref/testing.py:74: in receive_output
    return await self.output_queue.get()
../../lib/python3.6/site-packages/asgiref/timeout.py:68: in __aexit__
    self._do_exit(exc_type)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <asgiref.timeout.timeout object at 0x7f7bc7fb0048>, exc_type = <class 'concurrent.futures._base.CancelledError'>

    def _do_exit(self, exc_type: Type[BaseException]) -> None:
        if exc_type is asyncio.CancelledError and self._cancelled:
            self._cancel_handler = None
            self._task = None
>           raise asyncio.TimeoutError
E           concurrent.futures._base.TimeoutError

../../lib/python3.6/site-packages/asgiref/timeout.py:105: TimeoutError
========================================================== short test summary info ===========================================================
FAILED tests/test_http.py::test_handler_concurrent_requests - concurrent.futures._base.TimeoutError
======================================================== 1 failed, 71 passed in 5.93s ========================================================```

**Comment by carltongibson** [comment]
Ok, super thanks. I will have a play. Good work. 

(Be a few days...)

**Comment by yedpodtrzitko** [comment]
@AlexHill nice work, although there's one more place in [staticfiles.py](https://github.com/django/channels/blob/master/channels/staticfiles.py#L58) where `self.scope` remains used which is causing problem.

**Review by carltongibson — APPROVED** [review]
Good spot @yedpodtrzitko! I've adjusted that in c3cf5bea8eefe0aa5186dadd3bb26498e505434c. 

Let's have this. Thanks @AlexHill!

**Pull request merged**
