### PR TITLE
add in the file binding/websockets.py the condition

### PR DESCRIPTION
**Pull request by debianitram**

### CODE REVIEW

**Comment by proofit404** [comment]
`self.fields` can be a tuple for example. This way condition statement wont match, since you removed type cast.

**Comment by debianitram** [comment]
Sorry, but I'm not agree. If the fields property is a tuple with the element ('__all__'), python considers as a string '__all__'.

Execute: type(('__all__'))

Sorry my bad english. Gato! :P

**Comment by andrewgodwin** [comment]
I agree with Artem. In Python, `("__all__",)` is not equal to `"__all__"`.

**Comment by proofit404** [comment]
And `"__all__"` is not equal to `"__all__",`. I don't like this part of python syntax for sure.

**Comment by debianitram** [comment]
Ok, ("__all__"**,** ) is not equal to "__all__", thats true. 
What I want to say, is that if you considers the fields property with the value ('__all__', ) don't have any sence. 
You should specify in the documentation how to use this property adequately.
If I set fields property with value '__all__', when I use the method update not change data in database.

Sorry my english!

**Comment by debianitram** [comment]
__all__ *

**Comment by debianitram** [comment]
`__all__` *

**Comment by proofit404** [comment]
I don't see why `("__all__",)` can be illegal use case.  Django forms behave the same way. So at least we should keep things convenient.

**Comment by debianitram** [comment]
Ok, then:
`self.fields in ('__all__', ['__all__'], ('__all__',))` ¿?

**Comment by andrewgodwin** [comment]
Binding is now gone, so closing this, sorry we never got to merging it!

**Pull request closed without merging**
